#include "action.h"

static const Action_Data_List  action_data_list[ACTION__COUNT] = {
    [ACTION_MOUSE_DOWN_LEFT]    = ACTION_DATA_POINT,
    [ACTION_MOUSE_DOWN_RIGHT]   = ACTION_DATA_POINT,
    [ACTION_MOUSE_DOWN_MIDDLE]  = ACTION_DATA_POINT,
    [ACTION_MOUSE_UP_LEFT]      = ACTION_DATA_POINT,
    [ACTION_MOUSE_UP_RIGHT]     = ACTION_DATA_POINT,
    [ACTION_MOUSE_UP_MIDDLE]    = ACTION_DATA_POINT,
    [ACTION_MOUSE_MOVE]         = ACTION_DATA_INT,
    [ACTION_SELECT_UP]          = ACTION_DATA_INT,
    [ACTION_SELECT_DOWN]        = ACTION_DATA_INT,
    [ACTION_SELECT_LEFT]        = ACTION_DATA_INT,
    [ACTION_SELECT_RIGHT]       = ACTION_DATA_INT,
};



